### ISSUE TITLE
Not working😐 even though I saw the dates

### ISSUE THREAD

**Issue by GITHUB-sys-998** [iamrohitagg/GitHub_Graph#8]
I forked this Repository then I copy the code of this forked Repository, then change the directory into `cd Github_Graph` then I type this command next `npm install`
And after installation I type `node index.js` and I see the dates

![Welcome - Visual Studio Code 4_24_2021 5_36_32 AM](https://user-images.githubusercontent.com/81162159/115953729-b25de800-a51f-11eb-8e4c-f7924f4f5fda.png)

 then I'm excited to check and refresh my profile but still the same not working, please answer me 

![GITHUB-sys-998 — Mozilla Firefox 4_24_2021 5_37_26 AM](https://user-images.githubusercontent.com/81162159/115953759-d7525b00-a51f-11eb-96f1-13664c8f5502.png)

**Comment by iamrohitagg** [comment]
I think we can close the issue now.
