### ISSUE TITLE
COMMIT DATES

### ISSUE THREAD

**Issue by GL4D1AT0R** [iamrohitagg/GitHub_Graph#9]
Hello Rohit, 

Whenever I try and run this code all the commits take place in 2020 june - 2021 JAN and not further, How do I make this so that its to 2021 and 2019?

**Comment by iamrohitagg** [comment]
Hi @DEV0616 Please make sure the "y" parameter for DATE object is 2. Then it will commit at a date 2 years before the current. For a more old year you can have 3 as value for "y".
